"""Add query_category to Grievance model

Revision ID: 4f654bdd8d8c
Revises: 
Create Date: 2025-05-22 12:50:41.232175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f654bdd8d8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('faculties')  # Removed because it causes errors if the table does not exist
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('query_category', sa.String(length=100), nullable=False, server_default='Other'))
    # Remove the server_default after the column is created (optional, for future inserts to require explicit value)
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.alter_column('query_category', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grievances', schema=None) as batch_op:
        batch_op.drop_column('query_category')

    op.create_table('faculties',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
